{
  "openapi": "3.0.3",
  "info": {
    "title": "Phonebook API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080/api",
      "description": "Local server"
    }
  ],
  "paths": {
    "/auth/signup": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Create user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "email": "john@gmail.com",
                "password": "pass123"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User is created",
            "content": {
              "application/json": {
                "example": {
                  "status": "success",
                  "code": 201,
                  "user": {
                    "email": "john@gmail.com",
                    "subscription": "starter",
                    "avatarURL": "//www.gravatar.com/avatar/9b5071cb25a9029111f37805536bef38"
                  }
                }
              }
            }
          },
          "409": {
            "description": "This email address is already taken"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Login user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "email": "john@gmail.com",
                "password": "pass123"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User is created",
            "content": {
              "application/json": {
                "example": {
                  "status": "success",
                  "code": 200,
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGUzYzA1Zjg5OWJhNDNhNzg2YTBmYyIsImlhdCI6MTY0NTEwMTEzOX0.nzzV2xAJKy2iT_ChIhrb3irGZejVhkCi0Ko-aHYQQlQ",
                  "user": {
                    "email": "john3@gmail.com",
                    "subscription": "starter",
                    "avatarURL": "//www.gravatar.com/avatar/9b5071cb25a9029111f37805536bef38"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Email or password is wrong"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/auth/logout": {
      "get": {
        "tags": ["Authentication"],
        "summary": "Logout user",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Token is given to the user",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User logged out",
            "content": {
              "application/json": {
                "example": {
                  "status": "success",
                  "code": 200,
                  "message": "Succeeded logout"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/users/currents": {
      "get": {
        "tags": ["User"],
        "summary": "Get info about current user",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Token is given to the user",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Info about current user",
            "content": {
              "application/json": {
                "example": {
                  "status": "success",
                  "code": 200,
                  "user": {
                    "email": "john@gmail.com",
                    "subscription": "starter",
                    "avatarURL": "//www.gravatar.com/avatar/9b5071cb25a9029111f37805536bef38"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/users/subscription": {
      "patch": {
        "tags": ["User"],
        "summary": "Change a type of subscription",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Token is given to the user",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserSubscription"
              },
              "example": {
                "subscription": "pro"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "A type of subscription is changed",
            "content": {
              "application/json": {
                "example": {
                  "status": "success",
                  "code": 200,
                  "user": {
                    "email": "john3@gmail.com",
                    "subscription": "pro",
                    "avatarURL": "//www.gravatar.com/avatar/9b5071cb25a9029111f37805536bef38"
                  }
                }
              }
            }
          },
          "400": {
            "description": "There is no such a type of subscription"
          },
          "401": {
            "description": "Not authorized"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/users/avatar": {
      "patch": {
        "tags": ["User"],
        "summary": "Change an avatar",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Token is given to the user",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multiform/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "avatar": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The avatar is changed",
            "content": {
              "application/json": {
                "example": {
                  "status": "success",
                  "code": 200,
                  "user": {
                    "status": "success",
                    "code": 200,
                    "avatarURL": "public\\avatars\\1645128831807_h5sqvJdlOlY.jpg"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/contacts": {
      "get": {
        "tags": ["Contacts"],
        "summary": "Get all contacts",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Token is given to the user",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Contacts are received",
            "content": {
              "application/json": {
                "example": [
                  {
                    "_id": "620fa25c7d81d1e701f55a3d",
                    "name": "Homer Simpson",
                    "phone": "555-55-55",
                    "favorite": false,
                    "owner": {
                      "_id": "620e3c05f899ba43a786a0fc",
                      "email": "oldisc3@gmail.com"
                    },
                    "createdAt": "2022-02-18T13:42:52.136Z",
                    "updatedAt": "2022-02-18T13:42:52.136Z"
                  },
                  {
                    "_id": "620fa7e2fcdea0618a8a6f4b",
                    "name": "Marge Simpson",
                    "phone": "555-55-55",
                    "favorite": false,
                    "owner": {
                      "_id": "620e3c05f899ba43a786a0fc",
                      "email": "oldisc3@gmail.com"
                    },
                    "createdAt": "2022-02-18T14:06:26.159Z",
                    "updatedAt": "2022-02-18T14:06:26.159Z"
                  },
                  {
                    "_id": "620fa7f9fcdea0618a8a6f4e",
                    "name": "Lisa Simpson",
                    "phone": "555-55-55",
                    "favorite": false,
                    "owner": {
                      "_id": "620e3c05f899ba43a786a0fc",
                      "email": "oldisc3@gmail.com"
                    },
                    "createdAt": "2022-02-18T14:06:49.669Z",
                    "updatedAt": "2022-02-18T14:06:49.669Z"
                  },
                  {
                    "_id": "620fa80efcdea0618a8a6f51",
                    "name": "Bart Simpson",
                    "phone": "555-55-55",
                    "favorite": false,
                    "owner": {
                      "_id": "620e3c05f899ba43a786a0fc",
                      "email": "oldisc3@gmail.com"
                    },
                    "createdAt": "2022-02-18T14:07:10.138Z",
                    "updatedAt": "2022-02-18T14:07:10.138Z"
                  }
                ]
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "500": {
            "description": "Server error"
          }
        }
      },
      "post": {
        "tags": ["Contacts"],
        "summary": "Add a new contact",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Token is given to the user",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Contact"
              },
              "example": {
                "name": "Homer Simpson",
                "phone": "555-55-55"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Contacts are received",
            "content": {
              "application/json": {
                "example": {
                  "status": "success",
                  "code": 201,
                  "contact": {
                    "name": "Homer Simpson",
                    "phone": "555-55-55",
                    "favorite": false,
                    "owner": "620e3c05f899ba43a786a0fc",
                    "_id": "620fa25c7d81d1e701f55a3d",
                    "createdAt": "2022-02-18T13:42:52.136Z",
                    "updatedAt": "2022-02-18T13:42:52.136Z"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/contacts/{contactId}": {
      "get": {
        "tags": ["Contacts"],
        "summary": "Get contact by Id",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Token is given to the user",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "path",
            "name": "contactId",
            "required": true,
            "description": "Contact Id",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Contacts are received",
            "content": {
              "application/json": {
                "example": {
                  "status": "success",
                  "code": 200,
                  "contact": {
                    "_id": "620fa25c7d81d1e701f55a3d",
                    "name": "Homer Simpson",
                    "phone": "555-55-55",
                    "favorite": false,
                    "owner": {
                      "_id": "620e3c05f899ba43a786a0fc",
                      "email": "oldisc3@gmail.com"
                    },
                    "createdAt": "2022-02-18T13:42:52.136Z",
                    "updatedAt": "2022-02-18T13:42:52.136Z"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "The contact is not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User email (needs to confirm)"
          },
          "password": {
            "type": "string",
            "description": "User password (min 5 characters)"
          }
        }
      },
      "UserSubscription": {
        "type": "object",
        "required": ["subscription"],
        "properties": {
          "subscription": {
            "type": "string",
            "description": "A type of subscription",
            "enum": ["starter", "pro", "business"]
          }
        }
      },
      "Contact": {
        "type": "object",
        "required": ["name", "phone"],
        "properties": {
          "name": {
            "type": "string",
            "description": "Contact's name"
          },
          "phone": {
            "type": "string",
            "description": "Contact's phone number"
          }
        }
      }
    }
  }
}
